# Generated by Django 3.2.15 on 2022-08-28 09:04

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220826_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Admin', max_length=100, no_check_for_status=True),
        ),
    ]
